[package]
name = "node-sys"
version = "0.1.0"
authors = ["Darin Morrison <freebroccolo@users.noreply.github.com>"]
license = "(Apache-2.0 OR MIT)"
readme = "README.md"
categories = ["wasm"]
repository = "https://github.com/freebroccolo/node-sys"
description = """
Raw bindings to the Node.js API for projects using wasm-bindgen.
"""
edition = "2018"

[badges]
maintenance = { status = "experimental" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
assert = []
async_hooks = []
buffer = []
child_process = []
cluster = []
console = []
constants = []
crypto = []
dgram = []
dns = []
domain = []
events = []
fs = []
http = []
http2 = []
https = []
inspector = []
module = []
net = []
os = []
path = []
perf_hook = []
process = []
punycode = []
querystring = []
readline = []
repl = []
stream = []
string_decoder = []
timers = []
tls = []
trace_events = []
tty = []
url = []
util = []
v8 = []
vm = []
worker_threads = []
zlib = []

[dependencies]
serde = "1.0.90"
serde_derive = "1.0.90"

[dependencies.js-sys]
version = "0.3.19"
features = []

[dependencies.web-sys]
version = "0.3.19"
features = []

[dependencies.wasm-bindgen]
version = "0.2.42"
features = ["serde-serialize", "nightly"]

[patch.crates-io.node-sys]
path = "."

[workspace]
members = [
  "examples/cwd"
]
